### ISSUE TITLE
"L" in line 219

### ISSUE THREAD

**Issue by Ju43** [zku/SuperHaxagon#2]
Hey there is an L in line 219 wich has to be removed
auto hWnd = FindWindow(nullptr, L"Super Hexagon");
It's the one right before " "Super Hexagon"); " 
I hope I could help :)

**Comment by zku** [comment]
The `L` there is not an accident; I'm using the wide Windows API: http://msdn.microsoft.com/en-us/library/windows/desktop/dd374089(v=vs.85).aspx

The `L` C++ prefix defines a wide string literal: http://stackoverflow.com/questions/13087219/what-exactly-is-the-l-prefix-in-c

If you are getting compiler errors (presumably in Visual Studio), go to the `Project settings > General` and set `Character Set` to **Use Unicode Character Set**
